name: Build and Cache Frontend/Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: vodenje-stroskov/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('vodenje-stroskov/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci
      working-directory: vodenje-stroskov

    - name: Build application
      run: npm run build
      working-directory: vodenje-stroskov
