name: Run React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: vodenje-stroskov

      - name: Run tests and generate coverage report
        run: |
          npm test -- --watchAll=false --coverage
        working-directory: vodenje-stroskov

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: react-coverage
          path: vodenje-stroskov/coverage
