name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  # Testiranje frontenda
  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: vodenje-stroskov

    - name: Run tests and generate coverage report
      run: |
        npm test -- --watchAll=false --coverage
      working-directory: vodenje-stroskov

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: react-coverage
        path: vodenje-stroskov/coverage

  # Gradnja Docker slike in nalaganje na Docker Hub - Development
  dockerize-and-push-dev:
    needs: test-frontend
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:dev ./vodenje-stroskov
        docker tag ${{ secrets.DOCKER_USERNAME }}/frontend:dev ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:dev
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

  # Deploy na Firebase Hosting
  deploy-to-firebase:
    needs: test-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci
      working-directory: vodenje-stroskov

    - name: Build application
      run: npm run build
      working-directory: vodenje-stroskov

    - name: Setup Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: vodenje-stroskov

  # Uvedba na GitHub Pages
  deploy-pages:
    needs: test-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build application
      run: npm run build
      working-directory: vodenje-stroskov

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: vodenje-stroskov/build
